# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#FLIGHTS SEEDS
flight1 = Flight.create(flight:870)
flight2 = Flight.create(flight:1280)
flight3 = Flight.create(flight:1550)
flight4 = Flight.create(flight:760)
flight5 = Flight.create(flight:1190)
flight6 = Flight.create(flight:1440)
flight7 = Flight.create(flight:550)
flight8 = Flight.create(flight:970)
flight9 = Flight.create(flight:1250)
flight10 = Flight.create(flight:1820)
flight11 = Flight.create(flight:1450)
flight12 = Flight.create(flight:1910)
flight13 = Flight.create(flight:1881)
flight14 = Flight.create(flight:650)
flight15 = Flight.create(flight:1100)
flight16 = Flight.create(flight:2550)
flight17 = Flight.create(flight:4455)
flight18 = Flight.create(flight:1775)
flight19 = Flight.create(flight:978)
flight20 = Flight.create(flight:905)
flight21 = Flight.create(flight:1570)

#SEEDING PILOTS
pilot1 = Pilot.create(name: "Leah Smith", image: "/images/Female1.png")
pilot2 = Pilot.create(name: "John Baker", image: "/images/Male1.png")
pilot3 = Pilot.create(name: "Katherine Jones", image: "/images/Female2.png")
pilot4 = Pilot.create(name: "Tom Anderson", image: "/images/Male2.png")
pilot5 = Pilot.create(name: "Clair Adams", image: "/images/Female3.png")
pilot6 = Pilot.create(name: "Michael Hamilton", image: "/images/Male3.png")
pilot7 = Pilot.create(name: "Amy Jackson", image: "/images/Female4.png")
pilot8 = Pilot.create(name: "James Henry", image: "/images/Male4.png")
pilot9 = Pilot.create(name: "Julia Michaels", image: "/images/Female5.png")
pilot10 = Pilot.create(name: "Bruce Stein", image: "/images/Male5.png")
pilot11 = Pilot.create(name: "Mike Bradshaw", image: "/images/Male6.png")
pilot12 = Pilot.create(name: "Bill Peterson", image: "/images/Male7.png")
pilot13 = Pilot.create(name: "John Andrews", image: "/images/Male8.png")
pilot14 = Pilot.create(name: "Philip Michelson", image: "/images/Male9.png")
pilot15 = Pilot.create(name: "Gene Thompson", image: "/images/Male10.png")
pilot16 = Pilot.create(name: "William Baker", image: "/images/Male11.png")
pilot17 = Pilot.create(name: "Sam Johnson", image: "/images/Male12.png")
pilot18 = Pilot.create(name: "Chris Shepherd", image: "/images/Male13.png")
pilot19 = Pilot.create(name: "Adam White", image: "/images/Male14.png")
pilot20 = Pilot.create(name: "Joseph Law", image: "/images/Male15.png")
pilot21 = Pilot.create(name: "Eric Ibanez", image: "/images/Male16.png")

#SEEDING LOGS
all_pilots = Pilot.all.to_a
all_flights = Flight.all.to_a


log1 = Log.create(pilot_id: all_pilots.pop.id, flight_id: all_flights.pop.id, origin: "ATL", destination: "BOS", duration: 2, distance: 800, date: "02/11/2021", notes: "Clear communication with Air Traffic Control. Grounds crew got us turn around quickly for an on time departure. Flight crew interacted with passengers very professionally. Very little turbulance with a smooth take off and landing.", air_traffic_control: 5, grounds_crew: 4.5, flight_attendants: 5, co_pilot: 5)
log2 = Log.create(pilot_id: all_pilots.pop.id, flight_id: all_flights.pop.id, origin: "LAX", destination: "PHX", duration: 3.5, distance: 800, date: "08/08/2021", notes: "Clear communication with Air Traffic Control. Grounds crew got us turn around quickly for an on time departure. Flight crew interacted with passengers very professionally. Very little turbulance with a smooth take off and landing.", air_traffic_control: 4.5, grounds_crew: 4.5, flight_attendants: 5, co_pilot: 5 )
log3 = Log.create(pilot_id: all_pilots.pop.id, flight_id: all_flights.pop.id, origin: "DFW", destination: "LGA", duration: 1.5, distance: 800, date: "21/03/2021", notes: "Clear communication with Air Traffic Control. Grounds crew got us turn around quickly for an on time departure. Flight crew interacted with passengers very professionally. Very little turbulance with a smooth take off and landing.", air_traffic_control: 5, grounds_crew: 5, flight_attendants: 4.5, co_pilot: 5 )
log4 = Log.create(pilot_id: all_pilots.pop.id, flight_id: all_flights.pop.id, origin: "SEA", destination: "ATL", duration: 2.5, distance: 800, date: "11/09/2021", notes: "Clear communication with Air Traffic Control. Grounds crew got us turn around quickly for an on time departure. Flight crew interacted with passengers very professionally. Very little turbulance with a smooth take off and landing.", air_traffic_control: 5, grounds_crew: 5, flight_attendants: 5, co_pilot: 5 )
log5 = Log.create(pilot_id: all_pilots.pop.id, flight_id: all_flights.pop.id, origin: "MSY", destination: "BOS", duration: 3, distance: 800, date: "29/11/2021", notes: "Clear communication with Air Traffic Control. Grounds crew got us turn around quickly for an on time departure. Flight crew interacted with passengers very professionally. Very little turbulance with a smooth take off and landing.", air_traffic_control: 3.5, grounds_crew: 4, flight_attendants: 5, co_pilot: 5 )
log6 = Log.create(pilot_id: all_pilots.pop.id, flight_id: all_flights.pop.id, origin: "IAH", destination: "SNA", duration: 2, distance: 800, date: "15/05/2021", notes: "Clear communication with Air Traffic Control. Grounds crew got us turn around quickly for an on time departure. Flight crew interacted with passengers very professionally. Very little turbulance with a smooth take off and landing.", air_traffic_control: 5, grounds_crew: 5, flight_attendants: 5, co_pilot: 4.5 )
log7 = Log.create(pilot_id: all_pilots.pop.id, flight_id: all_flights.pop.id, origin: "ATL", destination: "BOS", duration: 3.5, distance: 800, date: "19/03/2021", notes: "Clear communication with Air Traffic Control. Grounds crew got us turn around quickly for an on time departure. Flight crew interacted with passengers very professionally. Very little turbulance with a smooth take off and landing.", air_traffic_control: 5, grounds_crew: 4.5, flight_attendants: 5, co_pilot: 5 )
log8 = Log.create(pilot_id: all_pilots.pop.id, flight_id: all_flights.pop.id, origin: "ORD", destination: "LGA", duration: 1.5, distance: 800, date: "25/06/2021", notes: "Clear communication with Air Traffic Control. Grounds crew got us turn around quickly for an on time departure. Flight crew interacted with passengers very professionally. Very little turbulance with a smooth take off and landing.", air_traffic_control: 5, grounds_crew: 5, flight_attendants: 4.5, co_pilot: 5 )
log9 = Log.create(pilot_id: all_pilots.pop.id, flight_id: all_flights.pop.id, origin: "ATL", destination: "SFO", duration: 2, distance: 800, date: "08/02/2021", notes: "Clear communication with Air Traffic Control. Grounds crew got us turn around quickly for an on time departure. Flight crew interacted with passengers very professionally. Very little turbulance with a smooth take off and landing.", air_traffic_control: 5, grounds_crew: 4, flight_attendants: 5, co_pilot: 4.5 )
log10 = Log.create(pilot_id: all_pilots.pop.id, flight_id: all_flights.pop.id, origin: "SLC", destination: "LGA", duration: 4, distance: 800, date: "01/09/2021", notes: "Clear communication with Air Traffic Control. Grounds crew got us turn around quickly for an on time departure. Flight crew interacted with passengers very professionally. Very little turbulance with a smooth take off and landing.", air_traffic_control: 5, grounds_crew: 4.5, flight_attendants: 5, co_pilot: 5 )
log11 = Log.create(pilot_id: all_pilots.pop.id, flight_id: all_flights.pop.id, origin: "JFK", destination: "SAN", duration: 3, distance: 800, date: "07/10/2021", notes: "Clear communication with Air Traffic Control. Grounds crew got us turn around quickly for an on time departure. Flight crew interacted with passengers very professionally. Very little turbulance with a smooth take off and landing.", air_traffic_control: 4.5, grounds_crew: 5, flight_attendants: 4.5, co_pilot: 5 )
log12 = Log.create(pilot_id: all_pilots.pop.id, flight_id: all_flights.pop.id, origin: "SFO", destination: "ATL", duration: 2.5, distance: 800, date: "16/04/2021", notes: "Clear communication with Air Traffic Control. Grounds crew got us turn around quickly for an on time departure. Flight crew interacted with passengers very professionally. Very little turbulance with a smooth take off and landing.", air_traffic_control: 5, grounds_crew: 4.5, flight_attendants: 5, co_pilot: 5 )
log13 = Log.create(pilot_id: all_pilots.pop.id, flight_id: all_flights.pop.id, origin: "OKC", destination: "SNA", duration: 1.5, distance: 800, date: "22/10/2021", notes: "Clear communication with Air Traffic Control. Grounds crew got us turn around quickly for an on time departure. Flight crew interacted with passengers very professionally. Very little turbulance with a smooth take off and landing.", air_traffic_control: 5, grounds_crew: 5, flight_attendants: 5, co_pilot: 5 )
log14 = Log.create(pilot_id: all_pilots.pop.id, flight_id: all_flights.pop.id, origin: "OAK", destination: "LGA", duration: 2.5, distance: 800, date: "28/08/2021", notes: "Clear communication with Air Traffic Control. Grounds crew got us turn around quickly for an on time departure. Flight crew interacted with passengers very professionally. Very little turbulance with a smooth take off and landing.", air_traffic_control: 5, grounds_crew: 4.5, flight_attendants: 5, co_pilot: 4.5 )
log15 = Log.create(pilot_id: all_pilots.pop.id, flight_id: all_flights.pop.id, origin: "SNA", destination: "JFK", duration: 3.5, distance: 800, date: "19/07/2021", notes: "Clear communication with Air Traffic Control. Grounds crew got us turn around quickly for an on time departure. Flight crew interacted with passengers very professionally. Very little turbulance with a smooth take off and landing.", air_traffic_control: 5, grounds_crew: 5, flight_attendants: 4, co_pilot: 5 )
log16 = Log.create(pilot_id: all_pilots.pop.id, flight_id: all_flights.pop.id, origin: "MIA", destination: "LAX", duration: 2, distance: 800, date: "14/05/2021", notes: "Clear communication with Air Traffic Control. Grounds crew got us turn around quickly for an on time departure. Flight crew interacted with passengers very professionally. Very little turbulance with a smooth take off and landing.", air_traffic_control: 5, grounds_crew: 5, flight_attendants: 5, co_pilot: 5 )
log17 = Log.create(pilot_id: all_pilots.pop.id, flight_id: all_flights.pop.id, origin: "ATL", destination: "BOS", duration: 4.5, distance: 800, date: "12/08/2021", notes: "Clear communication with Air Traffic Control. Grounds crew got us turn around quickly for an on time departure. Flight crew interacted with passengers very professionally. Very little turbulance with a smooth take off and landing.", air_traffic_control: 5, grounds_crew: 4.5, flight_attendants: 5, co_pilot: 4.5 )
log18= Log.create(pilot_id: all_pilots.pop.id, flight_id: all_flights.pop.id, origin: "TPA", destination: "JFK", duration: 5, distance: 800, date: "02/05/2021", notes: "Clear communication with Air Traffic Control. Grounds crew got us turn around quickly for an on time departure. Flight crew interacted with passengers very professionally. Very little turbulance with a smooth take off and landing.", air_traffic_control: 5, grounds_crew: 4.5, flight_attendants: 5, co_pilot: 5 )
log19 = Log.create(pilot_id: all_pilots.pop.id, flight_id: all_flights.pop.id, origin: "ABQ", destination: "LGA", duration: 2, distance: 800, date: "08/06/2021", notes: "Clear communication with Air Traffic Control. Grounds crew got us turn around quickly for an on time departure. Flight crew interacted with passengers very professionally. Very little turbulance with a smooth take off and landing.", air_traffic_control: 4.5, grounds_crew: 4.5, flight_attendants: 4.5, co_pilot: 5 )
log20 = Log.create(pilot_id: all_pilots.pop.id, flight_id: all_flights.pop.id, origin: "DEN", destination: "ATL", duration: 2.5, distance: 800, date: "14/02/2021", notes: "Clear communication with Air Traffic Control. Grounds crew got us turn around quickly for an on time departure. Flight crew interacted with passengers very professionally. Very little turbulance with a smooth take off and landing.", air_traffic_control: 5, grounds_crew: 5, flight_attendants: 4.5, co_pilot: 5 )
log21 = Log.create(pilot_id: all_pilots.pop.id, flight_id: all_flights.pop.id, origin: "BOS", destination: "SLC", duration: 3, distance: 800, date: "10/06/2021", notes: "Clear communication with Air Traffic Control. Grounds crew got us turn around quickly for an on time departure. Flight crew interacted with passengers very professionally. Very little turbulance with a smooth take off and landing.", air_traffic_control: 5, grounds_crew: 5, flight_attendants: 5, co_pilot: 5 )